{
  "formatVersion": "1.1",
  "component": {
    "group": "com.objectfanatics",
    "module": "commons-kotlin",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "noatamdy3fcjznkra3czxokzva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-kotlin-0.0.1.jar",
          "url": "commons-kotlin-0.0.1.jar",
          "size": 1428,
          "sha512": "48e1162335af737fbcd6c7fac2689d0bd8fad04d30e672976cb3437cbfe8a0fc65b4cbb3d11c33cf32d4aced3cff37a0bd9fd6a423c611a354ea5f4bc11cb335",
          "sha256": "02c5f31fe3d82a17658970031b72e3fe4d567723c00bf8892f563c41c01f7245",
          "sha1": "8be3c075e10b5075791b0cc4f22bfda9a5ba0e1b",
          "md5": "f2e16ad8bb52da6fe9a08869186058d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "commons-kotlin-0.0.1.jar",
          "url": "commons-kotlin-0.0.1.jar",
          "size": 1428,
          "sha512": "48e1162335af737fbcd6c7fac2689d0bd8fad04d30e672976cb3437cbfe8a0fc65b4cbb3d11c33cf32d4aced3cff37a0bd9fd6a423c611a354ea5f4bc11cb335",
          "sha256": "02c5f31fe3d82a17658970031b72e3fe4d567723c00bf8892f563c41c01f7245",
          "sha1": "8be3c075e10b5075791b0cc4f22bfda9a5ba0e1b",
          "md5": "f2e16ad8bb52da6fe9a08869186058d4"
        }
      ]
    }
  ]
}
