{
  "formatVersion": "1.1",
  "component": {
    "group": "com.objectfanatics",
    "module": "commons-kotlin",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "wjjxuvd7nbdbnjc47og3c5w7lu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-kotlin-0.0.1-SNAPSHOT.jar",
          "url": "commons-kotlin-0.0.1-20200812.153622-1.jar",
          "size": 1428,
          "sha512": "a4bc18428d76f9298e180db8f58547762065cda83f5a96f37eb029a728ce85c764ce73b7a958d102caf26cbe14763554aa62acaffa7e2b834b5cd8a8e87266c7",
          "sha256": "720bf8c9b7034caaa39d6561f722fa06a26da70a5d8cf2c022ff8ca51b6237f4",
          "sha1": "69563b5b4d51b651671f87f564f55859c17be818",
          "md5": "4afef6386cf6b25665621803f087b35f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "commons-kotlin-0.0.1-SNAPSHOT.jar",
          "url": "commons-kotlin-0.0.1-20200812.153622-1.jar",
          "size": 1428,
          "sha512": "a4bc18428d76f9298e180db8f58547762065cda83f5a96f37eb029a728ce85c764ce73b7a958d102caf26cbe14763554aa62acaffa7e2b834b5cd8a8e87266c7",
          "sha256": "720bf8c9b7034caaa39d6561f722fa06a26da70a5d8cf2c022ff8ca51b6237f4",
          "sha1": "69563b5b4d51b651671f87f564f55859c17be818",
          "md5": "4afef6386cf6b25665621803f087b35f"
        }
      ]
    }
  ]
}
