{
  "formatVersion": "1.1",
  "component": {
    "group": "com.objectfanatics",
    "module": "commons-android",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "wjjxuvd7nbdbnjc47og3c5w7lu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "commons-android-0.0.1-SNAPSHOT.aar",
          "url": "commons-android-0.0.1-20200812.153622-1.aar",
          "size": 30788,
          "sha512": "5e9d74e3f4cbe045042005832b7f4a6f87500ed85bac18078dbd53f515c47df4fee13a462c2bec6274165e5fd71f3d70c2916b8176557ac31084fc35fa825244",
          "sha256": "6d5842867bb5e3229b0b9431d77531250bbd9852f6a565b207d9a3459f100e66",
          "sha1": "ab88ed432c55fea5045a4bcc2da11db25fe9053f",
          "md5": "13399caec2c3c508e1bf22440dacbc77"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.objectfanatics",
          "module": "commons-kotlin",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0-alpha06"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.0-alpha06"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "commons-android-0.0.1-SNAPSHOT.aar",
          "url": "commons-android-0.0.1-20200812.153622-1.aar",
          "size": 30788,
          "sha512": "5e9d74e3f4cbe045042005832b7f4a6f87500ed85bac18078dbd53f515c47df4fee13a462c2bec6274165e5fd71f3d70c2916b8176557ac31084fc35fa825244",
          "sha256": "6d5842867bb5e3229b0b9431d77531250bbd9852f6a565b207d9a3459f100e66",
          "sha1": "ab88ed432c55fea5045a4bcc2da11db25fe9053f",
          "md5": "13399caec2c3c508e1bf22440dacbc77"
        }
      ]
    }
  ]
}
