{
  "formatVersion": "1.1",
  "component": {
    "group": "com.objectfanatics",
    "module": "commons-android",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "noatamdy3fcjznkra3czxokzva"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "commons-android-0.0.1.aar",
          "url": "commons-android-0.0.1.aar",
          "size": 44661,
          "sha512": "36f7cc420d6f9f903f287ff37a1fa0ec5307e0acf34bc459a5cdb169ae33ee8e03e354b02026f3d36392ba840da1346230523b132acba5193e6e166d578ae8dd",
          "sha256": "389b3fe648d6cd032ca3bc900e9ad7558cfd5706d2f6e596d3aa1357e34fff7f",
          "sha1": "b5e6eb5666672cab1ca7758142d97380a97fefd5",
          "md5": "a7e0dd4303c941e318b8f388881376ea"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.objectfanatics",
          "module": "commons-kotlin",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0-alpha06"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.0-alpha06"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "commons-android-0.0.1.aar",
          "url": "commons-android-0.0.1.aar",
          "size": 44661,
          "sha512": "36f7cc420d6f9f903f287ff37a1fa0ec5307e0acf34bc459a5cdb169ae33ee8e03e354b02026f3d36392ba840da1346230523b132acba5193e6e166d578ae8dd",
          "sha256": "389b3fe648d6cd032ca3bc900e9ad7558cfd5706d2f6e596d3aa1357e34fff7f",
          "sha1": "b5e6eb5666672cab1ca7758142d97380a97fefd5",
          "md5": "a7e0dd4303c941e318b8f388881376ea"
        }
      ]
    }
  ]
}
