{
  "formatVersion": "1.1",
  "component": {
    "group": "com.objectfanatics",
    "module": "gradle-plugin-dynamicmodulesplugin",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "noatamdy3fcjznkra3czxokzva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-plugin-dynamicmodulesplugin-0.0.1.jar",
          "url": "gradle-plugin-dynamicmodulesplugin-0.0.1.jar",
          "size": 6153,
          "sha512": "00dfb2a681d350debfec366e9f21cec53916cf6c51515787a46087ec4612e4e741ed4ab5124f961cd18772176c13c363fc8e651ab77b96792dfbef5bdd1a9275",
          "sha256": "c1750bfbe5691bb542a7b3b1452c4fe1d252d519302b910dd45f844f097a1e1a",
          "sha1": "312c4e86fe532e496976c49bc0a6b294afea72a2",
          "md5": "277e3f48a90b92beea899b7f778617f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-dynamicmodulesplugin-0.0.1.jar",
          "url": "gradle-plugin-dynamicmodulesplugin-0.0.1.jar",
          "size": 6153,
          "sha512": "00dfb2a681d350debfec366e9f21cec53916cf6c51515787a46087ec4612e4e741ed4ab5124f961cd18772176c13c363fc8e651ab77b96792dfbef5bdd1a9275",
          "sha256": "c1750bfbe5691bb542a7b3b1452c4fe1d252d519302b910dd45f844f097a1e1a",
          "sha1": "312c4e86fe532e496976c49bc0a6b294afea72a2",
          "md5": "277e3f48a90b92beea899b7f778617f8"
        }
      ]
    }
  ]
}
